package io.github.yuko1101.JapanizedChat.utils

import net.minecraft.util.EnumChatFormatting
import java.io.BufferedReader
import java.io.IOException
import java.io.InputStreamReader
import java.net.HttpURLConnection
import java.net.URL
import java.net.URLEncoder
import java.util.*

object Translate {

    fun toKana(msg: String): String {
        var kana = msg
        kana = kana.replace("nn".toRegex(), "ん")
        kana = kana.replace("wwha".toRegex(), "っうぁ")
        kana = kana.replace("wwhi".toRegex(), "っうぃ")
        kana = kana.replace("wwhu".toRegex(), "っう")
        kana = kana.replace("wwhe".toRegex(), "っうぇ")
        kana = kana.replace("wwho".toRegex(), "っうぉ")
        kana = kana.replace("wwyi".toRegex(), "っゐ")
        kana = kana.replace("wwye".toRegex(), "っゑ")
        kana = kana.replace("xxa".toRegex(), "っぁ")
        kana = kana.replace("xxi".toRegex(), "っぃ")
        kana = kana.replace("xxu".toRegex(), "っぅ")
        kana = kana.replace("xxe".toRegex(), "っぇ")
        kana = kana.replace("xxo".toRegex(), "っぉ")
        kana = kana.replace("xxya".toRegex(), "っゃ")
        kana = kana.replace("xxyu".toRegex(), "っゅ")
        kana = kana.replace("xxyo".toRegex(), "っょ")
        kana = kana.replace("xxtu".toRegex(), "っっ")
        kana = kana.replace("lla".toRegex(), "っぁ")
        kana = kana.replace("lli".toRegex(), "っぃ")
        kana = kana.replace("llu".toRegex(), "っぅ")
        kana = kana.replace("lle".toRegex(), "っぇ")
        kana = kana.replace("llo".toRegex(), "っぉ")
        kana = kana.replace("llya".toRegex(), "っゃ")
        kana = kana.replace("llyu".toRegex(), "っゅ")
        kana = kana.replace("llyo".toRegex(), "っょ")
        kana = kana.replace("lltu".toRegex(), "っっ")
        kana = kana.replace("kka".toRegex(), "っか")
        kana = kana.replace("kki".toRegex(), "っき")
        kana = kana.replace("kku".toRegex(), "っく")
        kana = kana.replace("kke".toRegex(), "っけ")
        kana = kana.replace("kko".toRegex(), "っこ")
        kana = kana.replace("kkya".toRegex(), "っきゃ")
        kana = kana.replace("kkyi".toRegex(), "っきぃ")
        kana = kana.replace("kkyu".toRegex(), "っきゅ")
        kana = kana.replace("kkye".toRegex(), "っきぇ")
        kana = kana.replace("kkyo".toRegex(), "っきょ")
        kana = kana.replace("gga".toRegex(), "っが")
        kana = kana.replace("ggi".toRegex(), "っぎ")
        kana = kana.replace("ggu".toRegex(), "っぐ")
        kana = kana.replace("gge".toRegex(), "っげ")
        kana = kana.replace("ggo".toRegex(), "っご")
        kana = kana.replace("ggya".toRegex(), "っぎゃ")
        kana = kana.replace("ggyi".toRegex(), "っぎぃ")
        kana = kana.replace("ggyu".toRegex(), "っぎゅ")
        kana = kana.replace("ggye".toRegex(), "っぎぇ")
        kana = kana.replace("ggyo".toRegex(), "っぎょ")
        kana = kana.replace("ttsa".toRegex(), "っつぁ")
        kana = kana.replace("ttsi".toRegex(), "っつぃ")
        kana = kana.replace("ttsu".toRegex(), "っつ")
        kana = kana.replace("ttse".toRegex(), "っつぇ")
        kana = kana.replace("ttso".toRegex(), "っつぉ")
        kana = kana.replace("ssa".toRegex(), "っさ")
        kana = kana.replace("ssi".toRegex(), "っし")
        kana = kana.replace("ssu".toRegex(), "っす")
        kana = kana.replace("sse".toRegex(), "っせ")
        kana = kana.replace("sso".toRegex(), "っそ")
        kana = kana.replace("cca".toRegex(), "っか")
        kana = kana.replace("cci".toRegex(), "っし")
        kana = kana.replace("ccu".toRegex(), "っく")
        kana = kana.replace("cce".toRegex(), "っせ")
        kana = kana.replace("cco".toRegex(), "っこ")
        kana = kana.replace("ssha".toRegex(), "っしゃ")
        kana = kana.replace("sshi".toRegex(), "っし")
        kana = kana.replace("sshu".toRegex(), "っしゅ")
        kana = kana.replace("sshe".toRegex(), "っしぇ")
        kana = kana.replace("ssho".toRegex(), "っしょ")
        kana = kana.replace("ssya".toRegex(), "っしゃ")
        kana = kana.replace("ssyi".toRegex(), "っしぃ")
        kana = kana.replace("ssyu".toRegex(), "っしゅ")
        kana = kana.replace("ssye".toRegex(), "っしぇ")
        kana = kana.replace("ssyo".toRegex(), "っしょ")
        kana = kana.replace("zza".toRegex(), "っざ")
        kana = kana.replace("zzi".toRegex(), "っじ")
        kana = kana.replace("zzu".toRegex(), "っず")
        kana = kana.replace("zze".toRegex(), "っぜ")
        kana = kana.replace("zzo".toRegex(), "っぞ")
        kana = kana.replace("jja".toRegex(), "っじゃ")
        kana = kana.replace("jji".toRegex(), "っじ")
        kana = kana.replace("jju".toRegex(), "っじゅ")
        kana = kana.replace("jje".toRegex(), "っじぇ")
        kana = kana.replace("jjo".toRegex(), "っじょ")
        kana = kana.replace("jjya".toRegex(), "っじゃ")
        kana = kana.replace("jjyi".toRegex(), "っじぃ")
        kana = kana.replace("jjyu".toRegex(), "っじゅ")
        kana = kana.replace("jjye".toRegex(), "っじぇ")
        kana = kana.replace("jjyo".toRegex(), "っじょ")
        kana = kana.replace("zzya".toRegex(), "っじゃ")
        kana = kana.replace("zzyi".toRegex(), "っじぃ")
        kana = kana.replace("zzyu".toRegex(), "っじゅ")
        kana = kana.replace("zzye".toRegex(), "っじぇ")
        kana = kana.replace("zzyo".toRegex(), "っじょ")
        kana = kana.replace("tta".toRegex(), "った")
        kana = kana.replace("tti".toRegex(), "っち")
        kana = kana.replace("ttu".toRegex(), "っつ")
        kana = kana.replace("tte".toRegex(), "って")
        kana = kana.replace("tto".toRegex(), "っと")
        kana = kana.replace("ttya".toRegex(), "っちゃ")
        kana = kana.replace("ttyi".toRegex(), "っちぃ")
        kana = kana.replace("ttyu".toRegex(), "っちゅ")
        kana = kana.replace("ttye".toRegex(), "っちぇ")
        kana = kana.replace("ttyo".toRegex(), "っちょ")
        kana = kana.replace("ttha".toRegex(), "ってゃ")
        kana = kana.replace("tthi".toRegex(), "ってぃ")
        kana = kana.replace("tthu".toRegex(), "ってゅ")
        kana = kana.replace("tthe".toRegex(), "ってぇ")
        kana = kana.replace("ttho".toRegex(), "ってょ")
        kana = kana.replace("ccya".toRegex(), "っちゃ")
        kana = kana.replace("ccyi".toRegex(), "っちぃ")
        kana = kana.replace("ccyu".toRegex(), "っちゅ")
        kana = kana.replace("ccye".toRegex(), "っちぇ")
        kana = kana.replace("ccyo".toRegex(), "っちょ")
        kana = kana.replace("ccha".toRegex(), "っちゃ")
        kana = kana.replace("cchi".toRegex(), "っち")
        kana = kana.replace("cchu".toRegex(), "っちゅ")
        kana = kana.replace("cche".toRegex(), "っちぇ")
        kana = kana.replace("ccho".toRegex(), "っちょ")
        kana = kana.replace("dda".toRegex(), "っだ")
        kana = kana.replace("ddi".toRegex(), "っぢ")
        kana = kana.replace("ddu".toRegex(), "っづ")
        kana = kana.replace("dde".toRegex(), "っで")
        kana = kana.replace("ddo".toRegex(), "っど")
        kana = kana.replace("ddya".toRegex(), "っぢゃ")
        kana = kana.replace("ddyi".toRegex(), "っぢぃ")
        kana = kana.replace("ddyu".toRegex(), "っぢゅ")
        kana = kana.replace("ddye".toRegex(), "っぢぇ")
        kana = kana.replace("ddyo".toRegex(), "っぢょ")
        kana = kana.replace("ddha".toRegex(), "っでゃ")
        kana = kana.replace("ddhi".toRegex(), "っでぃ")
        kana = kana.replace("ddhu".toRegex(), "っでゅ")
        kana = kana.replace("ddhe".toRegex(), "っでぇ")
        kana = kana.replace("ddho".toRegex(), "っでょ")
        kana = kana.replace("ppha".toRegex(), "っふぁ")
        kana = kana.replace("pphi".toRegex(), "っふぃ")
        kana = kana.replace("pphu".toRegex(), "っふ")
        kana = kana.replace("pphe".toRegex(), "っふぇ")
        kana = kana.replace("ppho".toRegex(), "っふぉ")
        kana = kana.replace("hha".toRegex(), "っは")
        kana = kana.replace("hhi".toRegex(), "っひ")
        kana = kana.replace("hhu".toRegex(), "っふ")
        kana = kana.replace("hhe".toRegex(), "っへ")
        kana = kana.replace("hho".toRegex(), "っほ")
        kana = kana.replace("hhya".toRegex(), "っひゃ")
        kana = kana.replace("hhyi".toRegex(), "っひぃ")
        kana = kana.replace("hhyu".toRegex(), "っひゅ")
        kana = kana.replace("hhye".toRegex(), "っひぇ")
        kana = kana.replace("hhyo".toRegex(), "っひょ")
        kana = kana.replace("ffa".toRegex(), "っふぁ")
        kana = kana.replace("ffi".toRegex(), "っふぃ")
        kana = kana.replace("ffu".toRegex(), "っふ")
        kana = kana.replace("ffe".toRegex(), "っふぇ")
        kana = kana.replace("ffo".toRegex(), "っふぉ")
        kana = kana.replace("ppa".toRegex(), "っぱ")
        kana = kana.replace("ppi".toRegex(), "っぴ")
        kana = kana.replace("ppu".toRegex(), "っぷ")
        kana = kana.replace("ppe".toRegex(), "っぺ")
        kana = kana.replace("ppo".toRegex(), "っぽ")
        kana = kana.replace("ppya".toRegex(), "っぴゃ")
        kana = kana.replace("ppyi".toRegex(), "っぴぃ")
        kana = kana.replace("ppyu".toRegex(), "っぴゅ")
        kana = kana.replace("ppye".toRegex(), "っぴぇ")
        kana = kana.replace("ppyo".toRegex(), "っぴょ")
        kana = kana.replace("bba".toRegex(), "っば")
        kana = kana.replace("bbi".toRegex(), "っび")
        kana = kana.replace("bbu".toRegex(), "っぶ")
        kana = kana.replace("bbe".toRegex(), "っべ")
        kana = kana.replace("bbo".toRegex(), "っぼ")
        kana = kana.replace("bbya".toRegex(), "っびゃ")
        kana = kana.replace("bbyi".toRegex(), "っびぃ")
        kana = kana.replace("bbyu".toRegex(), "っびゅ")
        kana = kana.replace("bbye".toRegex(), "っびぇ")
        kana = kana.replace("bbyo".toRegex(), "っびょ")
        kana = kana.replace("vva".toRegex(), "っヴァ")
        kana = kana.replace("vvi".toRegex(), "っヴィ")
        kana = kana.replace("vvu".toRegex(), "っヴ")
        kana = kana.replace("vve".toRegex(), "っヴェ")
        kana = kana.replace("vvo".toRegex(), "っヴォ")
        kana = kana.replace("vvya".toRegex(), "っヴャ")
        kana = kana.replace("vvyu".toRegex(), "っヴュ")
        kana = kana.replace("vvyo".toRegex(), "っヴョ")
        kana = kana.replace("mma".toRegex(), "っま")
        kana = kana.replace("mmi".toRegex(), "っみ")
        kana = kana.replace("mmu".toRegex(), "っむ")
        kana = kana.replace("mme".toRegex(), "っめ")
        kana = kana.replace("mmo".toRegex(), "っも")
        kana = kana.replace("mmya".toRegex(), "っみゃ")
        kana = kana.replace("mmyi".toRegex(), "っみぃ")
        kana = kana.replace("mmyu".toRegex(), "っみゅ")
        kana = kana.replace("mmye".toRegex(), "っみぇ")
        kana = kana.replace("mmyo".toRegex(), "っみょ")
        kana = kana.replace("rrya".toRegex(), "っりゃ")
        kana = kana.replace("rryi".toRegex(), "っりぃ")
        kana = kana.replace("rryu".toRegex(), "っりゅ")
        kana = kana.replace("rrye".toRegex(), "っりぇ")
        kana = kana.replace("rryo".toRegex(), "っりょ")
        kana = kana.replace("yya".toRegex(), "っや")
        kana = kana.replace("yyu".toRegex(), "っゆ")
        kana = kana.replace("yye".toRegex(), "っいぇ")
        kana = kana.replace("yyo".toRegex(), "っよ")
        kana = kana.replace("rra".toRegex(), "っら")
        kana = kana.replace("rri".toRegex(), "っり")
        kana = kana.replace("rru".toRegex(), "っる")
        kana = kana.replace("rre".toRegex(), "っれ")
        kana = kana.replace("rro".toRegex(), "っろ")
        kana = kana.replace("wwa".toRegex(), "っわ")
        kana = kana.replace("wwi".toRegex(), "っうぃ")
        kana = kana.replace("wwu".toRegex(), "っう")
        kana = kana.replace("wwe".toRegex(), "っうぇ")
        kana = kana.replace("wwo".toRegex(), "っを")
        kana = kana.replace("wha".toRegex(), "うぁ")
        kana = kana.replace("whi".toRegex(), "うぃ")
        kana = kana.replace("whu".toRegex(), "う")
        kana = kana.replace("whe".toRegex(), "うぇ")
        kana = kana.replace("who".toRegex(), "うぉ")
        kana = kana.replace("wyi".toRegex(), "ゐ")
        kana = kana.replace("wye".toRegex(), "ゑ")
        kana = kana.replace("xa".toRegex(), "ぁ")
        kana = kana.replace("xi".toRegex(), "ぃ")
        kana = kana.replace("xu".toRegex(), "ぅ")
        kana = kana.replace("xe".toRegex(), "ぇ")
        kana = kana.replace("xo".toRegex(), "ぉ")
        kana = kana.replace("xya".toRegex(), "ゃ")
        kana = kana.replace("xyu".toRegex(), "ゅ")
        kana = kana.replace("xyo".toRegex(), "ょ")
        kana = kana.replace("xtu".toRegex(), "っ")
        kana = kana.replace("la".toRegex(), "ぁ")
        kana = kana.replace("li".toRegex(), "ぃ")
        kana = kana.replace("lu".toRegex(), "ぅ")
        kana = kana.replace("le".toRegex(), "ぇ")
        kana = kana.replace("lo".toRegex(), "ぉ")
        kana = kana.replace("lya".toRegex(), "ゃ")
        kana = kana.replace("lyu".toRegex(), "ゅ")
        kana = kana.replace("lyo".toRegex(), "ょ")
        kana = kana.replace("ltu".toRegex(), "っ")
        kana = kana.replace("ka".toRegex(), "か")
        kana = kana.replace("ki".toRegex(), "き")
        kana = kana.replace("ku".toRegex(), "く")
        kana = kana.replace("ke".toRegex(), "け")
        kana = kana.replace("ko".toRegex(), "こ")
        kana = kana.replace("kya".toRegex(), "きゃ")
        kana = kana.replace("kyi".toRegex(), "きぃ")
        kana = kana.replace("kyu".toRegex(), "きゅ")
        kana = kana.replace("kye".toRegex(), "きぇ")
        kana = kana.replace("kyo".toRegex(), "きょ")
        kana = kana.replace("ga".toRegex(), "が")
        kana = kana.replace("gi".toRegex(), "ぎ")
        kana = kana.replace("gu".toRegex(), "ぐ")
        kana = kana.replace("ge".toRegex(), "げ")
        kana = kana.replace("go".toRegex(), "ご")
        kana = kana.replace("gya".toRegex(), "ぎゃ")
        kana = kana.replace("gyi".toRegex(), "ぎぃ")
        kana = kana.replace("gyu".toRegex(), "ぎゅ")
        kana = kana.replace("gye".toRegex(), "ぎぇ")
        kana = kana.replace("gyo".toRegex(), "ぎょ")
        kana = kana.replace("tsa".toRegex(), "つぁ")
        kana = kana.replace("tsi".toRegex(), "つぃ")
        kana = kana.replace("tsu".toRegex(), "つ")
        kana = kana.replace("tse".toRegex(), "つぇ")
        kana = kana.replace("tso".toRegex(), "つぉ")
        kana = kana.replace("sa".toRegex(), "さ")
        kana = kana.replace("si".toRegex(), "し")
        kana = kana.replace("su".toRegex(), "す")
        kana = kana.replace("se".toRegex(), "せ")
        kana = kana.replace("so".toRegex(), "そ")
        kana = kana.replace("ca".toRegex(), "か")
        kana = kana.replace("ci".toRegex(), "し")
        kana = kana.replace("cu".toRegex(), "く")
        kana = kana.replace("ce".toRegex(), "せ")
        kana = kana.replace("co".toRegex(), "こ")
        kana = kana.replace("sha".toRegex(), "しゃ")
        kana = kana.replace("shi".toRegex(), "し")
        kana = kana.replace("shu".toRegex(), "しゅ")
        kana = kana.replace("she".toRegex(), "しぇ")
        kana = kana.replace("sho".toRegex(), "しょ")
        kana = kana.replace("sya".toRegex(), "しゃ")
        kana = kana.replace("syi".toRegex(), "しぃ")
        kana = kana.replace("syu".toRegex(), "しゅ")
        kana = kana.replace("sye".toRegex(), "しぇ")
        kana = kana.replace("syo".toRegex(), "しょ")
        kana = kana.replace("za".toRegex(), "ざ")
        kana = kana.replace("zi".toRegex(), "じ")
        kana = kana.replace("zu".toRegex(), "ず")
        kana = kana.replace("ze".toRegex(), "ぜ")
        kana = kana.replace("zo".toRegex(), "ぞ")
        kana = kana.replace("ja".toRegex(), "じゃ")
        kana = kana.replace("ji".toRegex(), "じ")
        kana = kana.replace("ju".toRegex(), "じゅ")
        kana = kana.replace("je".toRegex(), "じぇ")
        kana = kana.replace("jo".toRegex(), "じょ")
        kana = kana.replace("jya".toRegex(), "じゃ")
        kana = kana.replace("jyi".toRegex(), "じぃ")
        kana = kana.replace("jyu".toRegex(), "じゅ")
        kana = kana.replace("jye".toRegex(), "じぇ")
        kana = kana.replace("jyo".toRegex(), "じょ")
        kana = kana.replace("zya".toRegex(), "じゃ")
        kana = kana.replace("zyi".toRegex(), "じぃ")
        kana = kana.replace("zyu".toRegex(), "じゅ")
        kana = kana.replace("zye".toRegex(), "じぇ")
        kana = kana.replace("zyo".toRegex(), "じょ")
        kana = kana.replace("ta".toRegex(), "た")
        kana = kana.replace("ti".toRegex(), "ち")
        kana = kana.replace("tu".toRegex(), "つ")
        kana = kana.replace("te".toRegex(), "て")
        kana = kana.replace("to".toRegex(), "と")
        kana = kana.replace("tya".toRegex(), "ちゃ")
        kana = kana.replace("tyi".toRegex(), "ちぃ")
        kana = kana.replace("tyu".toRegex(), "ちゅ")
        kana = kana.replace("tye".toRegex(), "ちぇ")
        kana = kana.replace("tyo".toRegex(), "ちょ")
        kana = kana.replace("tha".toRegex(), "てゃ")
        kana = kana.replace("thi".toRegex(), "てぃ")
        kana = kana.replace("thu".toRegex(), "てゅ")
        kana = kana.replace("the".toRegex(), "てぇ")
        kana = kana.replace("tho".toRegex(), "てょ")
        kana = kana.replace("cya".toRegex(), "ちゃ")
        kana = kana.replace("cyi".toRegex(), "ちぃ")
        kana = kana.replace("cyu".toRegex(), "ちゅ")
        kana = kana.replace("cye".toRegex(), "ちぇ")
        kana = kana.replace("cyo".toRegex(), "ちょ")
        kana = kana.replace("cha".toRegex(), "ちゃ")
        kana = kana.replace("chi".toRegex(), "ち")
        kana = kana.replace("chu".toRegex(), "ちゅ")
        kana = kana.replace("che".toRegex(), "ちぇ")
        kana = kana.replace("cho".toRegex(), "ちょ")
        kana = kana.replace("da".toRegex(), "だ")
        kana = kana.replace("di".toRegex(), "ぢ")
        kana = kana.replace("du".toRegex(), "づ")
        kana = kana.replace("de".toRegex(), "で")
        kana = kana.replace("do".toRegex(), "ど")
        kana = kana.replace("dya".toRegex(), "ぢゃ")
        kana = kana.replace("dyi".toRegex(), "ぢぃ")
        kana = kana.replace("dyu".toRegex(), "ぢゅ")
        kana = kana.replace("dye".toRegex(), "ぢぇ")
        kana = kana.replace("dyo".toRegex(), "ぢょ")
        kana = kana.replace("dha".toRegex(), "でゃ")
        kana = kana.replace("dhi".toRegex(), "でぃ")
        kana = kana.replace("dhu".toRegex(), "でゅ")
        kana = kana.replace("dhe".toRegex(), "でぇ")
        kana = kana.replace("dho".toRegex(), "でょ")
        kana = kana.replace("na".toRegex(), "な")
        kana = kana.replace("ni".toRegex(), "に")
        kana = kana.replace("nu".toRegex(), "ぬ")
        kana = kana.replace("ne".toRegex(), "ね")
        kana = kana.replace("no".toRegex(), "の")
        kana = kana.replace("nya".toRegex(), "にゃ")
        kana = kana.replace("nyi".toRegex(), "にぃ")
        kana = kana.replace("nyu".toRegex(), "にゅ")
        kana = kana.replace("nye".toRegex(), "にぇ")
        kana = kana.replace("nyo".toRegex(), "にょ")
        kana = kana.replace("pha".toRegex(), "ふぁ")
        kana = kana.replace("phi".toRegex(), "ふぃ")
        kana = kana.replace("phu".toRegex(), "ふ")
        kana = kana.replace("phe".toRegex(), "ふぇ")
        kana = kana.replace("pho".toRegex(), "ふぉ")
        kana = kana.replace("ha".toRegex(), "は")
        kana = kana.replace("hi".toRegex(), "ひ")
        kana = kana.replace("hu".toRegex(), "ふ")
        kana = kana.replace("he".toRegex(), "へ")
        kana = kana.replace("ho".toRegex(), "ほ")
        kana = kana.replace("hya".toRegex(), "ひゃ")
        kana = kana.replace("hyi".toRegex(), "ひぃ")
        kana = kana.replace("hyu".toRegex(), "ひゅ")
        kana = kana.replace("hye".toRegex(), "ひぇ")
        kana = kana.replace("hyo".toRegex(), "ひょ")
        kana = kana.replace("fa".toRegex(), "ふぁ")
        kana = kana.replace("fi".toRegex(), "ふぃ")
        kana = kana.replace("fu".toRegex(), "ふ")
        kana = kana.replace("fe".toRegex(), "ふぇ")
        kana = kana.replace("fo".toRegex(), "ふぉ")
        kana = kana.replace("fya".toRegex(), "ふゃ")
        kana = kana.replace("fyi".toRegex(), "ふぃ")
        kana = kana.replace("fyu".toRegex(), "ふゅ")
        kana = kana.replace("fye".toRegex(), "ふぇ")
        kana = kana.replace("fyo".toRegex(), "ふょ")
        kana = kana.replace("pa".toRegex(), "ぱ")
        kana = kana.replace("pi".toRegex(), "ぴ")
        kana = kana.replace("pu".toRegex(), "ぷ")
        kana = kana.replace("pe".toRegex(), "ぺ")
        kana = kana.replace("po".toRegex(), "ぽ")
        kana = kana.replace("pya".toRegex(), "ぴゃ")
        kana = kana.replace("pyi".toRegex(), "ぴぃ")
        kana = kana.replace("pyu".toRegex(), "ぴゅ")
        kana = kana.replace("pye".toRegex(), "ぴぇ")
        kana = kana.replace("pyo".toRegex(), "ぴょ")
        kana = kana.replace("ba".toRegex(), "ば")
        kana = kana.replace("bi".toRegex(), "び")
        kana = kana.replace("bu".toRegex(), "ぶ")
        kana = kana.replace("be".toRegex(), "べ")
        kana = kana.replace("bo".toRegex(), "ぼ")
        kana = kana.replace("bya".toRegex(), "びゃ")
        kana = kana.replace("byi".toRegex(), "びぃ")
        kana = kana.replace("byu".toRegex(), "びゅ")
        kana = kana.replace("bye".toRegex(), "びぇ")
        kana = kana.replace("byo".toRegex(), "びょ")
        kana = kana.replace("va".toRegex(), "ヴァ")
        kana = kana.replace("vi".toRegex(), "ヴィ")
        kana = kana.replace("vu".toRegex(), "ヴ")
        kana = kana.replace("ve".toRegex(), "ヴェ")
        kana = kana.replace("vo".toRegex(), "ヴォ")
        kana = kana.replace("vya".toRegex(), "ヴャ")
        kana = kana.replace("vyu".toRegex(), "ヴュ")
        kana = kana.replace("vyo".toRegex(), "ヴョ")
        kana = kana.replace("ma".toRegex(), "ま")
        kana = kana.replace("mi".toRegex(), "み")
        kana = kana.replace("mu".toRegex(), "む")
        kana = kana.replace("me".toRegex(), "め")
        kana = kana.replace("mo".toRegex(), "も")
        kana = kana.replace("mya".toRegex(), "みゃ")
        kana = kana.replace("myi".toRegex(), "みぃ")
        kana = kana.replace("myu".toRegex(), "みゅ")
        kana = kana.replace("mye".toRegex(), "みぇ")
        kana = kana.replace("myo".toRegex(), "みょ")
        kana = kana.replace("rya".toRegex(), "りゃ")
        kana = kana.replace("ryi".toRegex(), "りぃ")
        kana = kana.replace("ryu".toRegex(), "りゅ")
        kana = kana.replace("rye".toRegex(), "りぇ")
        kana = kana.replace("ryo".toRegex(), "りょ")
        kana = kana.replace("ya".toRegex(), "や")
        kana = kana.replace("yu".toRegex(), "ゆ")
        kana = kana.replace("ye".toRegex(), "いぇ")
        kana = kana.replace("yo".toRegex(), "よ")
        kana = kana.replace("ra".toRegex(), "ら")
        kana = kana.replace("ri".toRegex(), "り")
        kana = kana.replace("ru".toRegex(), "る")
        kana = kana.replace("re".toRegex(), "れ")
        kana = kana.replace("ro".toRegex(), "ろ")
        kana = kana.replace("wa".toRegex(), "わ")
        kana = kana.replace("wi".toRegex(), "うぃ")
        kana = kana.replace("wu".toRegex(), "う")
        kana = kana.replace("we".toRegex(), "うぇ")
        kana = kana.replace("wo".toRegex(), "を")
        kana = kana.replace("a".toRegex(), "あ")
        kana = kana.replace("i".toRegex(), "い")
        kana = kana.replace("u".toRegex(), "う")
        kana = kana.replace("e".toRegex(), "え")
        kana = kana.replace("o".toRegex(), "お")
        kana = kana.replace("n".toRegex(), "ん")
        kana = kana.replace("!".toRegex(), "！")
        kana = kana.replace("\\?".toRegex(), "？")
        kana = kana.replace("~".toRegex(), "～")
        kana = kana.replace("-".toRegex(), "ー")
        kana = kana.replace("\\[".toRegex(), "「")
        kana = kana.replace("]".toRegex(), "」")
        kana = kana.replace(",".toRegex(), "、")
        return kana
    }

    fun convByGoogleIME(org: String): String {
        return conv(org, true)
    }

    @Deprecated("")
    fun convBySocialIME(org: String): String {
        return conv(org, false)
    }

    private fun conv(org: String, isGoogleIME: Boolean): String {
        if (org.length != 0) {
            var urlconn: HttpURLConnection? = null
            var reader: BufferedReader? = null
            try {
                val baseurl: String
                val encode: String
                if (isGoogleIME) {
                    baseurl = "http://www.google.com/transliterate?langpair=ja-Hira|ja&text=" + URLEncoder.encode(
                        org,
                        "UTF-8"
                    )
                    encode = "UTF-8"
                } else {
                    baseurl = "http://www.social-ime.com/api/?string=" + URLEncoder.encode(org, "UTF-8")
                    encode = "EUC_JP"
                }
                val url = URL(baseurl)
                urlconn = url.openConnection() as HttpURLConnection
                urlconn.requestMethod = "GET"
                urlconn.instanceFollowRedirects = false
                urlconn.connect()
                reader = BufferedReader(InputStreamReader(urlconn.inputStream, encode))
                var line: String?
                val result = StringBuilder()
                while (reader.readLine().also { line = it } != null) {
                    if (isGoogleIME) {
                        result.append(parseGoogleIMEResult(line!!))
                    } else {
                        result.append(pickFirstElement(line!!))
                    }
                }
                return result.toString()
            } catch (var24: IOException) {
                var24.printStackTrace()
            } finally {
                urlconn?.disconnect()
                if (reader != null) {
                    try {
                        reader.close()
                    } catch (ignored: IOException) {
                    }
                }
            }
        }
        return ""
    }

    private fun pickFirstElement(org: String): String {
        val index = org.indexOf("\t")
        return if (index == -1) org else org.substring(0, index)
    }

    private fun parseGoogleIMEResult(result: String): String {
        val buf = StringBuilder()
        var level = 0
        var index = 0
        while (index < result.length) {
            var nextStart: Int
            var nextEnd: Int
            if (level >= 3) {
                nextStart = result.indexOf("\"", index)
                nextEnd = result.indexOf("\"", nextStart + 1)
                if (nextStart == -1 || nextEnd == -1) {
                    return buf.toString()
                }
                buf.append(result, nextStart + 1, nextEnd)
                val next = result.indexOf("]", nextEnd)
                if (next == -1) {
                    return buf.toString()
                }
                --level
                index = next + 1
            } else {
                nextStart = result.indexOf("[", index)
                nextEnd = result.indexOf("]", index)
                if (nextStart == -1) {
                    return buf.toString()
                }
                index = if (nextStart < nextEnd) {
                    ++level
                    nextStart + 1
                } else {
                    --level
                    nextEnd + 1
                }
            }
        }
        return buf.toString()
    }
}